apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  serviceAccount: opentelemetry-operator
  config: |
    receivers:
      jaeger:
    processors:
      queued-retry:
    exporters:
      logging:
    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [queued-retry]
          exporters: [logging]