apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-app
  template:
    metadata:
      labels:
        app: telemetry-app
    spec:
      containers:
      - name: app
        env: 
        - name: PORT
          value: "4431"
        - name: COLLECTOR_ADDR
          value: http://otel-collector.opentelemetry.svc.cluster.local:14268
        image: telemetry-app:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "32Mi"
            cpu: "250m"
          requests:
            memory: "32Mi"
            cpu: "250m"
        ports:
        - name: http
          containerPort: 4431
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 4431
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 4431
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 1
